### ISSUE TITLE
packages in ubuntu

### ISSUE THREAD

**Issue by sacarde** [sveneschlbeck/att#2]
hi,
   which dependecies I have to install on ubuntu-18.04?

speech_recognition (I dont find it in repo)

pydub (python-pydub or python3-pydub)

pyaudiio (python-pyaudio or python3-pyaudio)

thank you

**Comment by sveneschlbeck** [comment]
Hey,

yes, and time if not already installed. That should be it.

**Comment by sacarde** [comment]
ok, but I dont find "speech_recognition"

and python or python3 ?

**Comment by sacarde** [comment]
ok, I installed dependencies...

and now? how to install "att" ?

**Comment by sveneschlbeck** [comment]
You don't need to install it, just run the module with ``python <name_of_module>``. Make sure to be in the directory of the module when executing it. Then it should start automatically...

**Comment by sacarde** [comment]
ah.... OK 


thank you

**Comment by sveneschlbeck** [comment]
Of course. If there should be more issues appearing, don't hesitate to ask :)
